### ISSUE TITLE
Elastic MSI GA

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/elastic-stack-installers#62]
**Describe the feature**:
MSI Installer packages exist since v6.8 but are still labeled as beta which leads to some confusion.
Since it is the standard way to install software on windows, please make it GA and officially support it.
Thank you very much.

**Elasticsearch version** (`bin/elasticsearch --version`):
6.8 to 7.6

**Comment by ygel** [comment]
Hello @Bernhard-Fluehmann ,

Elasticsearch MSI installer in on the roadmap in the near future. This repository will supersede the original one once Elasticsearch an Kibana MSI are  relesed.

Have a great day!

**Comment by Bernhard-Fluehmann** [comment]
Hello @ygel ,
Thank you for your fast reply. I am looking forward to find the installers released soon.

Kind regards and a great day to you as well!

**Comment by Bernhard-Fluehmann** [comment]
Hello @ygel ,
I have opened a [discussion](https://discuss.elastic.co/t/winlogbeat-msi-create-service/227267) today on Winlogbeat msi installer not creating a service. Do you know what may the problem?

**Comment by ygel** [comment]
I've replied to that discussion as well, please take a look :)

**Comment by Bernhard-Fluehmann** [comment]
Ok. Just have seen it. Thank you very much. CLI Support is nice. I will dive a bit more into the reason why the service is not created. Alternatively I will keep using the modified .ps script ported from an older version. This works for me so far.

**Comment by ygel** [comment]
Service *is* created it *not started* due to post-install changes which must be made by the user before starting the service. Once installer finishes and proper `winlogbeat.yml` file is created, run `net start winlogbeat` or start the service from the Services snap-in.

**Comment by Bernhard-Fluehmann** [comment]
net start did the trick. Now what is interesting ist that the service IS running and the beat is shipping and monitoring but I can not see it in the service snap in. When I do net start winlogbeat again it tells me the service is already running but net start alone again shows a whole bunch of services but not winlogbeat.

**Comment by Bernhard-Fluehmann** [comment]
Just found the issue: The service is called Elastic Winlogbeat ...
My fault! Problem solved :) Thank you very much again for your help.

**Comment by ygel** [comment]
Correct this is service *display name* , service *name* for CLI is still just *winlogbeat*. This is visible in the service properties window. Glad this was resolved for you!
